import type { CivicIssue } from "@/types/civic";

export const mockIssues: CivicIssue[] = [
  {
    id: "issue-behala-01",
    title: "Behala flooded lane with blocked drain",
    rawText: "Water is knee deep near the drain and plastic is blocking it.",
    cleanSummary: "Knee-deep water is collecting near a blocked drain in Behala.",
    mode: "monsoon_flood_dengue",
    category: "Waterlogging and drainage hazard",
    subcategories: ["waterlogging", "blocked drain"],
    severity: "high",
    riskFlags: ["waterlogging", "blocked drain", "plastic waste"],
    departmentSuggestions: ["Sewerage and Drainage", "Solid Waste Management"],
    locationText: "Behala, Banamali Naskar Road",
    landmark: "Near market lane",
    ward: "Ward 128",
    borough: "Borough XIV",
    lat: 22.4986,
    lng: 88.3137,
    status: "verified",
    createdAt: "2026-07-01T09:00:00.000Z",
    updatedAt: "2026-07-05T07:30:00.000Z",
    duplicateGroupId: "behala-flood-drain-01",
    verificationCount: 7,
    unresolvedConfirmations: 5
  },
  {
    id: "issue-behala-02",
    title: "Same Behala drain overflows after rain",
    rawText: "Drain mouth still blocked after rain, water entering homes.",
    cleanSummary: "The Behala flood point has repeated reports after fresh rain.",
    mode: "monsoon_flood_dengue",
    category: "Recurring waterlogging",
    subcategories: ["blocked drain", "waterlogging"],
    severity: "high",
    riskFlags: ["waterlogging", "blocked drain", "recurring hotspot"],
    departmentSuggestions: ["Sewerage and Drainage", "Solid Waste Management"],
    locationText: "Behala, Banamali Naskar Road",
    ward: "Ward 128",
    borough: "Borough XIV",
    status: "verified",
    createdAt: "2026-07-02T11:20:00.000Z",
    updatedAt: "2026-07-04T18:10:00.000Z",
    duplicateGroupId: "behala-flood-drain-01",
    verificationCount: 4,
    unresolvedConfirmations: 4
  },
  {
    id: "issue-garia-01",
    title: "Garia waterlogging hiding pothole",
    rawText: "Water has covered a pothole near the auto stand.",
    cleanSummary: "Rainwater is hiding a pothole on a busy Garia approach road.",
    mode: "monsoon_flood_dengue",
    category: "Hidden pothole under water",
    subcategories: ["waterlogging", "hidden pothole"],
    severity: "high",
    riskFlags: ["waterlogging", "fall risk", "hidden pothole"],
    departmentSuggestions: ["Roads", "Sewerage and Drainage"],
    locationText: "Garia, near auto stand",
    ward: "Ward 111",
    borough: "Borough XI",
    status: "new",
    createdAt: "2026-07-03T08:45:00.000Z",
    updatedAt: "2026-07-05T06:55:00.000Z",
    verificationCount: 3,
    unresolvedConfirmations: 3
  },
  {
    id: "issue-bansdroni-01",
    title: "Bansdroni stagnant water and mosquitoes",
    rawText: "Stagnant water has collected beside garbage; mosquitoes are increasing.",
    cleanSummary: "Stagnant water near garbage in Bansdroni is creating a dengue concern.",
    mode: "monsoon_flood_dengue",
    category: "Dengue risk",
    subcategories: ["stagnant water", "garbage"],
    severity: "high",
    riskFlags: ["dengue risk", "stagnant water", "garbage"],
    departmentSuggestions: ["Health", "Solid Waste Management", "Sewerage and Drainage"],
    locationText: "Bansdroni, Naktala connector lane",
    ward: "Ward 113",
    borough: "Borough XI",
    status: "in_progress",
    createdAt: "2026-07-02T15:30:00.000Z",
    updatedAt: "2026-07-05T09:20:00.000Z",
    verificationCount: 5,
    unresolvedConfirmations: 2
  },
  {
    id: "issue-amherst-01",
    title: "Amherst Street recurring flood point",
    rawText: "Waterlogging at Thanthania side again after short rain.",
    cleanSummary: "Amherst Street and Thanthania have a recurring monsoon waterlogging point.",
    mode: "monsoon_flood_dengue",
    category: "Recurring flood point",
    subcategories: ["waterlogging", "recurrence"],
    severity: "high",
    riskFlags: ["waterlogging", "recurring hotspot", "blocked drain"],
    departmentSuggestions: ["Sewerage and Drainage", "Roads"],
    locationText: "Amherst Street / Thanthania",
    ward: "Ward 38",
    borough: "Borough IV",
    status: "verified",
    createdAt: "2026-06-28T12:00:00.000Z",
    updatedAt: "2026-07-05T08:05:00.000Z",
    duplicateGroupId: "amherst-waterlogging-01",
    verificationCount: 7,
    unresolvedConfirmations: 6
  },
  {
    id: "issue-amherst-02",
    title: "Thanthania drain overflow reported again",
    rawText: "Same corner near Thanthania has drain overflow.",
    cleanSummary: "The same Amherst-Thanthania corner has repeated drain overflow reports.",
    mode: "monsoon_flood_dengue",
    category: "Drain overflow",
    subcategories: ["blocked drain", "waterlogging"],
    severity: "medium",
    riskFlags: ["blocked drain", "recurring hotspot"],
    departmentSuggestions: ["Sewerage and Drainage"],
    locationText: "Thanthania Kalibari approach",
    ward: "Ward 38",
    borough: "Borough IV",
    status: "duplicate",
    createdAt: "2026-07-04T10:00:00.000Z",
    updatedAt: "2026-07-04T10:30:00.000Z",
    duplicateGroupId: "amherst-waterlogging-01",
    verificationCount: 2,
    unresolvedConfirmations: 2
  },
  {
    id: "issue-bypass-01",
    title: "EM Bypass pothole after rain",
    rawText: "A large pothole opened after rain near the service lane.",
    cleanSummary: "A rain-damaged pothole on EM Bypass service lane needs marking and repair.",
    mode: "monsoon_flood_dengue",
    category: "Rain-damaged road",
    subcategories: ["pothole", "road damage"],
    severity: "medium",
    riskFlags: ["hidden pothole", "traffic hazard"],
    departmentSuggestions: ["Roads"],
    locationText: "EM Bypass service lane",
    ward: "Ward 109",
    borough: "Borough XII",
    status: "new",
    createdAt: "2026-07-05T05:40:00.000Z",
    updatedAt: "2026-07-05T05:40:00.000Z",
    verificationCount: 1,
    unresolvedConfirmations: 1
  },
  {
    id: "issue-kumartuli-01",
    title: "Kumartuli Puja prep blocking lane",
    rawText: "Puja preparation material is narrowing the lane and blocking access.",
    cleanSummary: "Puja preparation material in Kumartuli is narrowing a shared lane.",
    mode: "pujo_safety",
    category: "Temporary festival obstruction",
    subcategories: ["crowd route", "access"],
    severity: "medium",
    riskFlags: ["route obstruction", "accessibility risk"],
    departmentSuggestions: ["Police", "Ward Office"],
    locationText: "Kumartuli idol workshop lane",
    ward: "Ward 9",
    borough: "Borough I",
    status: "new",
    createdAt: "2026-09-25T14:30:00.000Z",
    updatedAt: "2026-09-25T16:00:00.000Z",
    verificationCount: 2,
    unresolvedConfirmations: 1
  },
  {
    id: "issue-pujo-exit-01",
    title: "Pujo exit narrow with exposed wiring",
    rawText: "Pandal exit is too narrow, wire is hanging near barricade.",
    cleanSummary: "A Pujo exit has crowd bottleneck and exposed wiring concerns.",
    mode: "pujo_safety",
    category: "Pujo temporary-city safety",
    subcategories: ["crowd bottleneck", "temporary wiring"],
    severity: "critical",
    riskFlags: ["crowd bottleneck", "temporary electrical hazard", "fire safety gap"],
    departmentSuggestions: ["Police", "Fire", "Lighting"],
    locationText: "South Kolkata Pujo para",
    ward: "Ward 90",
    borough: "Borough VIII",
    status: "verified",
    createdAt: "2026-10-01T19:30:00.000Z",
    updatedAt: "2026-10-02T12:00:00.000Z",
    duplicateGroupId: "pujo-exit-wire-01",
    verificationCount: 6,
    unresolvedConfirmations: 5
  },
  {
    id: "issue-pujo-exit-02",
    title: "Bamboo near Pujo gate holding rainwater",
    rawText: "Bamboo support near the gate is holding rainwater and mosquitoes.",
    cleanSummary: "Temporary Pujo bamboo infrastructure is holding rainwater near the gate.",
    mode: "pujo_safety",
    category: "Pujo dengue and route risk",
    subcategories: ["stagnant water", "temporary structure"],
    severity: "high",
    riskFlags: ["dengue risk", "route obstruction"],
    departmentSuggestions: ["Health", "Ward Office", "Solid Waste Management"],
    locationText: "South Kolkata Pujo para gate",
    ward: "Ward 90",
    borough: "Borough VIII",
    status: "verified",
    createdAt: "2026-10-01T21:00:00.000Z",
    updatedAt: "2026-10-02T11:00:00.000Z",
    duplicateGroupId: "pujo-exit-wire-01",
    verificationCount: 3,
    unresolvedConfirmations: 3
  },
  {
    id: "issue-post-pujo-01",
    title: "Leftover bamboo and plastic blocking drain",
    rawText: "Pandal waste is still blocking the footpath and drain two days after immersion.",
    cleanSummary: "Post-Pujo bamboo and plastic waste is blocking a footpath and drain.",
    mode: "post_pujo_cleanup",
    category: "Post-Pujo waste and restoration",
    subcategories: ["pandal waste", "drain obstruction"],
    severity: "high",
    riskFlags: ["cleanup overdue", "drain obstruction", "pedestrian obstruction"],
    departmentSuggestions: ["Solid Waste Management", "Sewerage and Drainage", "Roads"],
    locationText: "Rashbehari connector lane",
    ward: "Ward 85",
    borough: "Borough VIII",
    status: "new",
    createdAt: "2026-10-25T09:15:00.000Z",
    updatedAt: "2026-10-25T09:15:00.000Z",
    verificationCount: 2,
    unresolvedConfirmations: 2
  },
  {
    id: "issue-winter-market-01",
    title: "Winter market garbage burning and road dust",
    rawText: "Garbage is being burned beside a broken dusty road near the market.",
    cleanSummary: "Open burning beside a dusty broken market road is creating winter air risk.",
    mode: "winter_air_dust",
    category: "Winter air and dust hazard",
    subcategories: ["open burning", "road dust"],
    severity: "high",
    riskFlags: ["open burning", "air quality risk", "respiratory risk"],
    departmentSuggestions: ["Solid Waste Management", "Roads", "Environment"],
    locationText: "Lake Market side lane",
    ward: "Ward 87",
    borough: "Borough VIII",
    status: "verified",
    createdAt: "2026-01-12T07:20:00.000Z",
    updatedAt: "2026-01-12T08:30:00.000Z",
    verificationCount: 4,
    unresolvedConfirmations: 3
  },
  {
    id: "issue-summer-water-01",
    title: "Summer water shortage near broken tap",
    rawText: "No water in this lane since morning. Elderly people are waiting near the public tap.",
    cleanSummary: "A public tap is not supplying water during summer heat with elderly residents waiting.",
    mode: "summer_heat_water",
    category: "Heat and water stress",
    subcategories: ["water shortage", "vulnerable people affected"],
    severity: "high",
    riskFlags: ["water shortage", "heat stress", "vulnerable people affected"],
    departmentSuggestions: ["Water Supply", "Ward Office", "Health"],
    locationText: "Chetla para public tap",
    ward: "Ward 82",
    borough: "Borough IX",
    status: "in_progress",
    createdAt: "2026-04-18T06:40:00.000Z",
    updatedAt: "2026-04-18T10:00:00.000Z",
    verificationCount: 5,
    unresolvedConfirmations: 2
  },
  {
    id: "issue-wetlands-01",
    title: "Debris dumping near bheri",
    rawText: "Truck dumped debris near this bheri. Water channel is getting blocked.",
    cleanSummary: "Debris dumping near an East Kolkata Wetlands bheri is blocking a water channel.",
    mode: "wetlands_watch",
    category: "East Kolkata Wetlands evidence",
    subcategories: ["illegal dumping", "water-channel blockage"],
    severity: "high",
    riskFlags: ["dumping", "water-channel blockage", "ecological risk"],
    departmentSuggestions: ["Environment", "Solid Waste Management", "Pollution Control"],
    locationText: "East Kolkata Wetlands, Bantala side",
    ward: "Peri-urban edge",
    borough: "Wetlands watch",
    status: "verified",
    createdAt: "2026-05-08T16:15:00.000Z",
    updatedAt: "2026-05-08T17:20:00.000Z",
    verificationCount: 3,
    unresolvedConfirmations: 3
  },
  {
    id: "issue-everyday-light-01",
    title: "Broken streetlight near open manhole",
    rawText: "Streetlight is broken and an open manhole is hard to see at night.",
    cleanSummary: "A broken streetlight makes an open manhole difficult to see at night.",
    mode: "everyday",
    category: "Everyday para civic issue",
    subcategories: ["streetlighting", "manhole"],
    severity: "high",
    riskFlags: ["public safety risk", "fall risk"],
    departmentSuggestions: ["Lighting", "Sewerage and Drainage"],
    locationText: "Shyambazar para lane",
    ward: "Ward 11",
    borough: "Borough I",
    status: "new",
    createdAt: "2026-07-05T13:05:00.000Z",
    updatedAt: "2026-07-05T13:05:00.000Z",
    verificationCount: 1,
    unresolvedConfirmations: 1
  }
];
